### ISSUE TITLE
Clicking todo checkbox while editing throws error

### ISSUE THREAD

**Issue by zachbradshaw** [brijeshb42/medium-draft#117]
Seeing this on `0.5.6` and `0.6.0-beta1`. Seeing this while running in my project as well as running `medium-draft` locally and in the [demo editor](http://bitwiser.in/medium-draft/). 

Clicking a todo checkbox while editing throws these errors:
```
Uncaught DOMException: Failed to execute 'extend' on 'Selection': This Selection object doesn't have any Ranges.
    at addFocusToSelection (http://localhost:8080/index.bundle.js:75895:17)
    at setDraftEditorSelection (http://localhost:8080/index.bundle.js:75829:5)
    at DraftEditorLeaf._setSelection (http://localhost:8080/index.bundle.js:73867:5)
    at DraftEditorLeaf.componentDidUpdate (http://localhost:8080/index.bundle.js:73877:10)
    at commitLifeCycles (http://localhost:8080/index.bundle.js:47173:24)
    at commitAllLifeCycles (http://localhost:8080/index.bundle.js:48341:9)
    at HTMLUnknownElement.callCallback (http://localhost:8080/index.bundle.js:38937:14)
    at Object.invokeGuardedCallbackDev (http://localhost:8080/index.bundle.js:38976:16)
    at invokeGuardedCallback (http://localhost:8080/index.bundle.js:38833:27)
    at commitRoot (http://localhost:8080/index.bundle.js:48445:9)
```
```
The above error occurred in the <DraftEditorLeaf> component:
    in DraftEditorLeaf (created by DraftEditorBlock)
    in div (created by DraftEditorBlock)
    in DraftEditorBlock (created by TodoBlock)
    in div (created by TodoBlock)
    in TodoBlock (created by DraftEditorContents)
    in div (created by DraftEditorContents)
    in div (created by DraftEditorContents)
    in DraftEditorContents (created by DraftEditor)
    in div (created by DraftEditor)
    in div (created by DraftEditor)
    in div (created by DraftEditor)
    in DraftEditor (created by MediumDraftEditor)
    in div (created by MediumDraftEditor)
    in div (created by MediumDraftEditor)
    in MediumDraftEditor (created by TwoPizzaEditor)
    in div (created by TwoPizzaEditor)
    in TwoPizzaEditor (created by Route)
    in Route (created by App)
    in Switch (created by App)
    in main (created by App)
    in div (created by App)
    in Router (created by BrowserRouter)
    in BrowserRouter (created by App)
    in Provider (created by App)
    in App
```
With the debugger open in my app, the debugger hits a breakpoint on the error, then the page goes blank after resuming progress. With the debugger closed the page goes blank instantly after clicking the todo checkbox. I've noticed in the online demo that with the debugger closed the checkbox gets checked as expected, but the error is still being thrown.

Looks like this is a draft-js bug that should be fixed by updating draft-js to a newer version as mentioned [here](https://github.com/facebook/draft-js/pull/1190#issuecomment-341750278). Not sure of the side effects of updating though.

**Comment by brijeshb42** [comment]
This seems to happend in chrome. In firefox, its working fine. Updating `draft-js` may help.
